### ISSUE TITLE
Enable use of mongodb with credentials enforced (--auth)

### ISSUE THREAD

**Issue by referup-tarantegui** [scullxbones/mgo-statsd#5]
A mongodb stack with statsd container attached works fine. But when I'm enabling the use of credentials with --auth in mongodb. The statsd container remains in status restarting, these are the logs:

```
Sep 20 11:45:00 mongo1 docker/e50ce927e4ac[913]: goroutine 10 [running]:
Sep 20 11:45:00 mongo1 docker/e50ce927e4ac[913]: panic(0x7d7140, 0xc8200b8bc0)
Sep 20 11:45:00 mongo1 docker/e50ce927e4ac[913]: #011/usr/local/go/src/runtime/panic.go:481 +0x3e6
Sep 20 11:45:00 mongo1 docker/e50ce927e4ac[913]: main.serverStatus(0xc8200171d0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Sep 20 11:45:00 mongo1 docker/e50ce927e4ac[913]: #011/usr/src/mgo-statsd/main.go:97 +0x2e1
Sep 20 11:45:00 mongo1 docker/e50ce927e4ac[913]: main.main.func1(0xc820050740, 0x3b9aca00, 0xc8200171d0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x7ffe6cd82cfc, ...)
Sep 20 11:45:00 mongo1 docker/e50ce927e4ac[913]: #011/usr/src/mgo-statsd/main.go:298 +0xc5
Sep 20 11:45:00 mongo1 docker/e50ce927e4ac[913]: created by main.main
Sep 20 11:45:00 mongo1 docker/e50ce927e4ac[913]: #011/usr/src/mgo-statsd/main.go:307 +0xbe
Sep 20 11:45:07 mongo1 docker/e50ce927e4ac[913]: panic: not authorized on admin to execute command { serverStatus: 1 }
```

Can you provide some info for the use of credentials with statsd container.

**Comment by referup-tarantegui** [comment]
I've seen that on --help

```
  -mongo_pass string
        MongoDB Password
  -mongo_user string
        MongoDB User
```

I'm closing the issue
